import { PROFILE_TABS } from '@/enums/user.view';

export const profileTabs: PROFILE_TABS[] = [
    PROFILE_TABS.PROFILE,
    PROFILE_TABS.CLASS_SCHEDULE,
    PROFILE_TABS.GUARDIAN_INFORMATION,
    PROFILE_TABS.ACADEMIC_REPORT,
    PROFILE_TABS.COURSE_MANAGEMENT,
    PROFILE_TABS.ACADEMIC_RESULT,
    PROFILE_TABS.PAYMENT_DETAILS,
    PROFILE_TABS.CHANGE_PASSWORD,
];

export const profileTabNames = {
    [PROFILE_TABS.PROFILE]: 'Profile',
    [PROFILE_TABS.CLASS_SCHEDULE]: 'Class Schedule',
    [PROFILE_TABS.GUARDIAN_INFORMATION]: 'Guardian Information',
    [PROFILE_TABS.ACADEMIC_REPORT]: 'Academic Report',
    [PROFILE_TABS.COURSE_MANAGEMENT]: 'Course Management',
    [PROFILE_TABS.ACADEMIC_RESULT]: 'Academic Result',
    [PROFILE_TABS.PAYMENT_DETAILS]: 'Payment Details',
    [PROFILE_TABS.CHANGE_PASSWORD]: 'Change Password',
};
