import { PROFILE_TABS } from '@/enums/user.view';

export type userTab =
    | PROFILE_TABS.PROFILE
    | PROFILE_TABS.CLASS_SCHEDULE
    | PROFILE_TABS.GUARDIAN_INFORMATION
    | PROFILE_TABS.ACADEMIC_REPORT
    | PROFILE_TABS.COURSE_MANAGEMENT
    | PROFILE_TABS.ACADEMIC_RESULT
    | PROFILE_TABS.PAYMENT_DETAILS
    | PROFILE_TABS.CHANGE_PASSWORD;
