import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/libs/Providers";

// POPUP JS DEFAULT STYLE
// import "reactjs-popup/dist/index.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "University Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
          {/* <div id="portal">
            <div
              className=""
              style={{
                position: "fixed",
                inset: "0px",
                display: "flex",

                zIndex: "999",
                background: "rgba(0, 0, 0, 0.5)",
                pointerEvents: "auto",
              }}
            >
              <h1 style={{ textAlign: "center", zIndex: "9999" }}>Portal</h1>
            </div>
          </div> */}
        </body>
      </html>
    </Providers>
  );
}
